//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siglo21.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOLETA
    {
        public BOLETA()
        {
            this.METODO_PAGO = new HashSet<METODO_PAGO>();
        }
    
        public decimal NRO_BOLETA { get; set; }
        public System.DateTime FECHA_PAGO { get; set; }
        public decimal DETALLE_PEDIDO_1 { get; set; }
        public decimal DETALLE_PEDIDO { get; set; }
    
        public virtual DETALLE_PEDIDO DETALLE_PEDIDO1 { get; set; }
        public virtual ICollection<METODO_PAGO> METODO_PAGO { get; set; }
    }
}
