//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siglo21.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_INSUMO
    {
        public DETALLE_INSUMO()
        {
            this.INFORME = new HashSet<INFORME>();
        }
    
        public decimal ID_DETALLE_INSUMO { get; set; }
        public decimal ID_INSUMO { get; set; }
    
        public virtual INSUMO INSUMO { get; set; }
        public virtual ICollection<INFORME> INFORME { get; set; }
    }
}
