//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siglo21.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_PEDIDO
    {
        public DETALLE_PEDIDO()
        {
            this.BOLETA = new HashSet<BOLETA>();
        }
    
        public decimal DETALLE_PEDIDO1 { get; set; }
        public decimal TOTAL { get; set; }
        public decimal ID_INFORME { get; set; }
        public decimal NRO_RESERVA { get; set; }
    
        public virtual ICollection<BOLETA> BOLETA { get; set; }
        public virtual INFORME INFORME { get; set; }
        public virtual PEDIDO PEDIDO { get; set; }
    }
}
