//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siglo21.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFORME
    {
        public INFORME()
        {
            this.DETALLE_PEDIDO = new HashSet<DETALLE_PEDIDO>();
        }
    
        public decimal ID_INFORME { get; set; }
        public System.DateTime FECHA { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal ID_DETALLE_INSUMO { get; set; }
        public decimal ID_USUARIO { get; set; }
    
        public virtual DETALLE_INSUMO DETALLE_INSUMO { get; set; }
        public virtual ICollection<DETALLE_PEDIDO> DETALLE_PEDIDO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
