//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siglo21.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSUMO
    {
        public INSUMO()
        {
            this.DETALLE_INSUMO = new HashSet<DETALLE_INSUMO>();
        }
    
        public decimal ID_INSUMO { get; set; }
        public string NOMBRE_INSUMO { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal PRECIO_UNITARIO { get; set; }
        public decimal STOCK { get; set; }
        public decimal ID_USUARIO { get; set; }
    
        public virtual ICollection<DETALLE_INSUMO> DETALLE_INSUMO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
