//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siglo21.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESA
    {
        public MESA()
        {
            this.PEDIDO = new HashSet<PEDIDO>();
        }
    
        public decimal NRO_MESA { get; set; }
        public decimal CANT_SILLAS { get; set; }
        public decimal NRO_RESERVA { get; set; }
    
        public virtual RESERVA RESERVA { get; set; }
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
    }
}
