//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siglo21.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class METODO_PAGO
    {
        public decimal ID_METODO { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal NRO_BOLETA_1 { get; set; }
        public decimal NRO_BOLETA { get; set; }
    
        public virtual BOLETA BOLETA { get; set; }
    }
}
